<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
    <PackageReference Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" Version="18.0.36421.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Services\Products\Distribt.Services.Products.BusinessLogic\Distribt.Services.Products.BusinessLogic.csproj" />
    <ProjectReference Include="..\src\Services\Products\Distribt.Services.Products.Dtos\Distribt.Services.Products.Dtos.csproj" />
  </ItemGroup>
</Project>
