<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1"/>
        <PackageReference Include="Moq" Version="4.17.2" />
        <PackageReference Include="xunit.v3" Version="3.2.2" />
        <PackageReference Include="xunit.v3.runner.common" Version="3.2.2" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\Services\Products\Distribt.Services.Products.Api.Read\Distribt.Services.Products.Api.Read.csproj" />
      <ProjectReference Include="..\..\..\..\Services\Products\Distribt.Services.Products.Api.Write\Distribt.Services.Products.Api.Write.csproj" />
    </ItemGroup>

</Project>